apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myapp-replicaset
  labels:
    app:  myapp
    type: abc

spec:
  template:
    metadata:
      name: nginx-pod
      labels:
        type: front-end
    spec:
      containers:
        - image:  nginx
          name:  nginx
  replicas: 3
  selector:
    matchLabels:
      type: front-end

