apiVersion: v1
kind: ReplicationController
metadata:
  name: myfirst-rc
  labels:
    app:  myapp
    type: front-end

spec:
  template:
    metadata:
      name: nginx-pod
      labels:
        app: test
    spec:
      containers:
        - image:  nginx
          name:  nginx
  replicas: 3